# Generated by Django 3.1.2 on 2021-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
